config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'work'    => 'static_pages#work'
  get    'employ'  => 'static_pages#employ'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  scope "(:locale)", locale: /en|es/ do
  root to: 'welcome#index'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>

</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>

</p>

app/views/static_pages/employ.html.erb
<h1 class="center">EMPLOY</h1>

<div>
  <span class="" id="">
    <p> If you need some type of job done and you dont have the time, the skill or you're just too lazy to do it, just hop into the Liber app (mobile or web) and offer the job for a certain amount of money. 
    <hr></hr>
    <p class="center"><b>You can post a job <a href="">here</a></b><p></span>
    <hr></hr>
    <p>Employers can be <b>anyone</b>: Busy offices, your local pizza parlor, you or even me.</p>
    <p>The jobs offered can be <b>anything</b>: Getting someone coffee, mawing someones lawn, writing a line o code, teaching someone math and even getting a ping pong ball for the beerpong that your local frat house is throwing.</p>
    <p>The users that are inside a certain radius will get notified through the app and the ones that are willing to do the job will send you a "job confirmation". The willing employees may request a higher pay which you can accept, negotiate or decline</p>
    <p>If you accept: The user will inmediatelly put his/her hands to work and get your job done as fast and as effective as they can</p>
    <p>Details about the amount of time that the worker has left, the phone number of the worker and the exact location of the worker will be available to you during the time of the employment</p>
    <p>After the job is done you need to hop on again into the app and finish the ordeal by pressing the "Done" button if the job was done correctly and succesfully, or "Not Done" if it wasnt. </p>
      <p>If you pressed the <b>"Done"</b> button: This will transfer the amount of money that you offered to pay and if you found that the user did an amazing job you can be generous enough to give an extra tip through the app by pressing the "¿tip?" button.</p>
      <p>If you pressed the <b>"Not Done"</b> button: This will cancel any arrangement you had with the user and also any transaction you had with him or her.</p>
  </span>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>

</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Job Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>

<div class="jumbotron container-fluid center">
  <span id="welcome_jumbotron">
      <h1 id="welcome_to_liber"><%= t '.welcome' %></h1>
      <h2 ><b><%= t '.about_app1'%></b></h2>
      <h2 ><b><%= t '.about_app2'%></b></h2>
      <h2 ><b><%= t '.about_app3'%></b></h2>
      <br></br>
  </span>
  <div class="center" id="signup1">
    <h2 id="quote1"><b><%= t '.quote1'%></b></h2>
    <%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary", id:"signup_test"%>
  </div>
</div>

  <div id="howitworks">    
    <h1 class="center"><b><%= t '.howitworks'%></b></h1>
  </div>
    <div class="container-fluid" id="work">
        <span>
        <h1 class="left" id="work1"><b><%= t '.work1'%></b></h1>
        </span>
        <span class ="container-fluid" id="work_content">
          <p><%= t '.work1content1'%></p>
            <span>
            <p class="center"><b><%= t '.createprofile'%> <a href=""><%= t '.here'%></a></b></p>
            </span>
          <p><%= t '.work1content2'%></p>
          <p><%= t '.work1content3'%> <a href=""><%= t '.here'%></a> <%= t '.work1content4'%></p>
          <p><%= t '.work1content5'%></p>
          <p><%= t '.work1content6'%></p>
          <p><%= t '.work1content7'%></p>
          <p><b> <%= t '.work1content8'%> <a href=""><%= t '.vision'%></a>.</b></p>
          <p><b> <%= t '.work1content9'%> <a href=""><%= t '.here'%></a>.</b></p>
        </span>
      </div>
    </div>
    <div class="container-fluid" id="employ">
      <span>
      <h1 class="left" id="employ1"><b> <%= t '.employ1'%></b></h1>
      </span>
      <span>
        <span class ="container-fluid" id="employ_content">
          <p><%= t '.employ1content1'%></p>
            <p class="center"><b><%= t '.createprofile'%> <a href=""><%= t '.here'%></a></b></p>
          <p><%= t '.employ1content2'%></p>
          <p><%= t '.employ1content3'%></p>
          <p class="center"><b><%= t '.employ1content4'%> <a href=""><%= t '.here'%></a></b><p>
          <p> <%= t '.employ1content5'%></p>
          <p> <%= t '.employ1content6'%></p>
          <p> <%= t '.employ1content7'%></p>
          <p> <%= t '.employ1content8'%></p>
      </span>
    </div>

<!--
<section id="seventh_section">
  <div class="container-fluid">
    <div class="left" id="fibonacci1">
      <div class="rectangle1" id="fibo1rectangle1"></div>
        <div class="rectangle2" id="fibo1rectangle2"><small></small></div>
        <div class="rectangle3" id="fibo1rectangle3"><a class=""></a></div>
    </div>
    <div class="center" id="fibonacci2">
      <div class="rectangle1" id="fibo1rectangle1"></div>
        <div class="rectangle2" id="fibo1rectangle2"> <small></small></div>
        <div class="rectangle3" id="fibo1rectangle3"><a class=""></a></div>
    </div>
    <div class="right" id="fibonacci3">
      <div class="rectangle1" id="fibo1rectangle1"></div>
        <div class="rectangle2" id="fibo1rectangle2"> <small></small></div>
        <div class="rectangle3" id="fibo1rectangle3"><a class=""></a></div>
    </div>
  </div>
</section>
-->

<div id="statistics_section" class="container-fluid center">
  <p><b>300345</b> active users</p>
  <p><b>2000</b> jobs completed</p>
  <p><b>300</b> open positions</p>
</div>

<div class ="container-fluid" id="vision">
  <h1 class="center">VISION<span><%= link_to image_tag("Logo Ideas/logonew4.png", alt: "Liber logo", id:"evo1")%></span></h1>
    <p>Our vision as a company is to first create a platform that represents a new way for people to earn money and complete jobs. We will also try to incorporate users selling goods and also startups.</p>
    <p>Secondly we will create a sector for teaching. People will get taught skills so that they can open even more their horizon of job opportunities.</p>
    <p>After those two steps are established we will establish a feature that enables users to cooperate with each other for the completion of certain jobs. We want for this step to allow users to form small businesses within the platform.</p>
    <p>At this stage we expect a surge in the number of employments and in the number of active businesses within the platform. Our objective is to form an economy in a platform.</p>
    <p class="center"><b>Read an extended version of our vision <a>here</a></b></p>
</div>
<div class ="container-fluid" id="philosophy">
  <h1 class="center">PHILOSOPHY<span><%= link_to image_tag("Logo Ideas/logo1 dharma.png", alt: "Liber logo", id:"dharma1")%></span></h1>
    <p>Our main aim is to show the uniqueness of people and provide them with a platform that enables them to express themselves freely and without limitations. </p>
    <p>Our main goal as a company is to follow our human destiny through uncertainty and find something divine that is purely organic and unique to our nature. Our aim is to potentiate our inevitable symbiotic relationship with other human and sentient beings. A relationship that is possible only by our impulses towards creation, through cooperation and unification, that are intrinsic to our human natural manifestation.</p>
</div>

<div class="container-fluid" id="whoarewe">
  <h1 class="center">WHO ARE WE</h1>
  <br></br>
  <p class="center">Matías Mingo</p>
  <div class="center">
  <%= image_tag("matías2.png", :alt => "rss feed", :id=> "matias_photo")%>
  </div>
  <br></br>
  <p class="center side_description"><b>Founder and CEO</b></p>
  <p>Hi my name is Matías Mingo. Im a 20 year old student from Chile. Im also the founder and CEO of Liber.
  </p>
  <p>
    Between the things i consider myself to be are being an entrepreneur, a philosopher and a true lover of the world.
  </p>
  <p>Check my own documentation of what moves me to do stuff in life by visiting my personal website <a href="http://www.matias.life">www.matias.life</a></p>
</div>
<% end %>

app/views/static_pages/work.html.erb
<h1 class="center">WORK</h1>

<div class="" id="">
  <p>The first step of becoming a user of Liber is by creating a profile.</p>
  <hr></hr>
    <p class="center"><b>You can create a profile <a href="">here</a></b></p>
  <hr></hr>
  <p>On you profile you should include: Your name, your profile picture, a brief description of you as a person and your hustling spirit, a list of certain skills that you posses (if any), a list of jobs you are good at and a brief description of your goals and objectives in life. 
  <p>
  <p>After your profile has been created you are ready to start hustling</p>
  <p>Choose from a list of types of work that you would like to have </p>
  <p>After you finish filling out all of the important information you are ready to start your life as a hustler</p>
  <p> You can choose between being a full time or part time hustler. Full-time users get notified about jobs on a 24/7 shcedule. Part-time users get notified about jobs on a schedule of their choosing.</p>
  <p><b>This is the first version of the app so its functionality is very simple and straightforward. The most important thing is our <a href="">vision</a>.</b></p>
</div>