config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'work'    => 'static_pages#work'
  get    'employ'  => 'static_pages#employ'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  scope "(:locale)", locale: /en|es/ do
  root to: 'welcome#index'
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small> 
    <p>All Rights Reserved Liber and Unknomad inc by Matías Mingo</p>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<section id="header">
<header class="navbar navbar-fixed-top ">
    <span class="dropdown" id="glyphicon_hamburger">
      <span data-toggle="dropdown" class="glyphicon glyphicon-menu-hamburger dropdown-toggle">
      </span>
      <span>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li></li>
          <li class="divider"></li>
        </ul>
      </span>
    </span>
    <!--<span id="logo1">
    <%=link_to root_path do %>
      <span id="l1">L</span><span id="i1">I</span><span id="b1">B</span><span id="perthro1">ᛈ</span><span id="r1">R</span>
    <%end%>
    </span>-->
    <span>
    <%= link_to image_tag("Logo Ideas/liberlogonew5.png", alt: "Liber logo", :class => "Logo1 center"),
            'http://liber.life/' %>
    <%= link_to image_tag("Logo Ideas/logonew4.png", alt: "Liber logo", :class => "Logo2 "),
            'http://liber.life/' %>
    </span>
      <span id="header_nav_1">
        <nav class="relative">
          <ul class="nav navbar-nav navbar-right">
            <li ><%= link_to "Work",    work_path, id: "work2" %></li>
            <li ><%= link_to "Employ",    employ_path, id: "employ2"  %></li>
          </ul>
        </nav>
      </span>
      <span id ="header_nav_2">
        <nav class="relative">
          <ul class="nav navbar-nav navbar-right">
            <li ><%= link_to "Help",    help_path %></li>
            <% if logged_in? %>
              <li><%= link_to "Users", users_path %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Profile", current_user %></li>
                  <li><%= link_to "Settings", edit_user_path(current_user) %></li>

                  <li class="divider"></li>
                  <li>
                    <%= link_to "Log out", logout_path, method: "delete" %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li ><%= link_to "Log in", login_path %></li>
            <% end %>
          </ul>
        </nav>
      </span>
</header>
</div>
</section>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Droid+Sans">
    <%= render 'layouts/shim' %>
  </head>
  <body>
      <%= render 'layouts/header' %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %> 
      <%= debug(params) if Rails.env.development? %>
  </body>
</html>